config-version: 2
version: '0.1'

name: 'test'

test:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin
      password: admin
      port: 5432
      dbname: dbt
      threads: 4
